spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/rspcm_local}
    username: ${LOCAL_DB_USERNAME:postgres}
    password: ${LOCAL_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
